### PR TITLE
Save focus level on close

### PR DESCRIPTION
**Pull request by ergl**
I often use deep trees, and currently every time you reopen void, the view gets reset to the `home` level. This makes it so the view stack and the current focus view are restored between runs. Maybe it's not the best way to things (just exposing fields with `pub`), but it might be helpful anyway.

The changes should work on existing documents, as all the new proto fields are optional, but I haven't done exhaustive testing of this.

### CODE REVIEW

**Comment by alok** [comment]
If I run this, it seems to clear my current document (good thing I backed up). Other than that it seems to work, and it doesn't clear its own doc.

**Comment by ergl** [comment]
@alok Sorry to hear that! I should probably test this more. I did this change a long time ago and my document seems to work fine. Let me close it and I'll look at it again

**Comment by alok** [comment]
@ergl How did you autogenerate `data_model.rs` with the updated changes? I poked around the protobuf crate and had trouble figuring it out.

**Comment by ergl** [comment]
I installed the [`protobuf-codegen`](https://github.com/stepancheg/rust-protobuf/tree/master/protobuf-codegen) plugin for protoc. Once you have that installed, doing `protoc --rust_out src/pb/ include/model.proto` should do the trick.

**Pull request closed without merging**
